import type { Bin, ImpactMetric, PriorityBin } from '@/types';

export const bins: Bin[] = [
  {
    id: 'BIN-001',
    location: 'Central Plaza',
    zone: 'Zone A — Downtown',
    fillLevel: 92,
    status: 'critical',
    lastUpdated: '2 min ago',
    type: 'general',
    distance: 1.2,
    coordinates: { lat: 40.7589, lng: -73.9851 },
  },
  {
    id: 'BIN-002',
    location: 'Riverside Park North',
    zone: 'Zone B — Park District',
    fillLevel: 78,
    status: 'high',
    lastUpdated: '5 min ago',
    type: 'recycling',
    distance: 2.4,
    coordinates: { lat: 40.7614, lng: -73.9776 },
  },
  {
    id: 'BIN-003',
    location: 'Market Street',
    zone: 'Zone A — Downtown',
    fillLevel: 65,
    status: 'medium',
    lastUpdated: '8 min ago',
    type: 'general',
    distance: 0.8,
    coordinates: { lat: 40.7549, lng: -73.9840 },
  },
  {
    id: 'BIN-004',
    location: 'Tech Campus Building 3',
    zone: 'Zone C — Industrial',
    fillLevel: 45,
    status: 'low',
    lastUpdated: '12 min ago',
    type: 'organic',
    distance: 3.1,
    coordinates: { lat: 40.7490, lng: -73.9710 },
  },
  {
    id: 'BIN-005',
    location: 'Harbor View Apartments',
    zone: 'Zone B — Park District',
    fillLevel: 88,
    status: 'high',
    lastUpdated: '3 min ago',
    type: 'general',
    distance: 2.0,
    coordinates: { lat: 40.7620, lng: -73.9800 },
  },
  {
    id: 'BIN-006',
    location: 'University Quad',
    zone: 'Zone D — Campus',
    fillLevel: 30,
    status: 'low',
    lastUpdated: '15 min ago',
    type: 'recycling',
    distance: 4.2,
    coordinates: { lat: 40.7480, lng: -73.9855 },
  },
  {
    id: 'BIN-007',
    location: 'Greenfield Mall',
    zone: 'Zone C — Industrial',
    fillLevel: 98,
    status: 'critical',
    lastUpdated: '1 min ago',
    type: 'general',
    distance: 3.5,
    coordinates: { lat: 40.7520, lng: -73.9680 },
  },
  {
    id: 'BIN-008',
    location: 'Lakeside Promenade',
    zone: 'Zone B — Park District',
    fillLevel: 12,
    status: 'empty',
    lastUpdated: '20 min ago',
    type: 'organic',
    distance: 2.8,
    coordinates: { lat: 40.7635, lng: -73.9790 },
  },
  {
    id: 'BIN-009',
    location: 'City Hall East Wing',
    zone: 'Zone A — Downtown',
    fillLevel: 55,
    status: 'medium',
    lastUpdated: '10 min ago',
    type: 'recycling',
    distance: 1.5,
    coordinates: { lat: 40.7560, lng: -73.9860 },
  },
  {
    id: 'BIN-010',
    location: 'Stadium Parking Lot C',
    zone: 'Zone D — Campus',
    fillLevel: 72,
    status: 'high',
    lastUpdated: '6 min ago',
    type: 'general',
    distance: 4.8,
    coordinates: { lat: 40.7470, lng: -73.9820 },
  },
  {
    id: 'BIN-011',
    location: 'Northgate Transit Hub',
    zone: 'Zone A — Downtown',
    fillLevel: 40,
    status: 'low',
    lastUpdated: '14 min ago',
    type: 'recycling',
    distance: 1.8,
    coordinates: { lat: 40.7595, lng: -73.9870 },
  },
  {
    id: 'BIN-012',
    location: 'Southport Marina',
    zone: 'Zone C — Industrial',
    fillLevel: 85,
    status: 'high',
    lastUpdated: '4 min ago',
    type: 'organic',
    distance: 5.2,
    coordinates: { lat: 40.7500, lng: -73.9650 },
  },
];

export const priorityBins: PriorityBin[] = [
  {
    id: 'BIN-007',
    location: 'Greenfield Mall',
    zone: 'Zone C — Industrial',
    fillLevel: 98,
    lastUpdated: '1 min ago',
    reason: 'Near overflow — collection overdue',
  },
  {
    id: 'BIN-001',
    location: 'Central Plaza',
    zone: 'Zone A — Downtown',
    fillLevel: 92,
    lastUpdated: '2 min ago',
    reason: 'High-traffic area, filling rapidly',
  },
  {
    id: 'BIN-005',
    location: 'Harbor View Apartments',
    zone: 'Zone B — Park District',
    fillLevel: 88,
    lastUpdated: '3 min ago',
    reason: 'Residential density spike detected',
  },
  {
    id: 'BIN-012',
    location: 'Southport Marina',
    zone: 'Zone C — Industrial',
    fillLevel: 85,
    lastUpdated: '4 min ago',
    reason: 'Weekend event overflow expected',
  },
  {
    id: 'BIN-002',
    location: 'Riverside Park North',
    zone: 'Zone B — Park District',
    fillLevel: 78,
    lastUpdated: '5 min ago',
    reason: 'Recycling contamination risk',
  },
];

export const impactMetrics: ImpactMetric[] = [
  {
    id: 'co2',
    label: 'CO₂ Emissions Reduced',
    value: 2840,
    unit: 'kg',
    icon: 'Leaf',
    trend: 12.5,
    color: 'brand',
  },
  {
    id: 'fuel',
    label: 'Fuel Saved',
    value: 340,
    unit: 'L',
    icon: 'Fuel',
    trend: 8.2,
    color: 'teal',
  },
  {
    id: 'distance',
    label: 'Distance Optimized',
    value: 1820,
    unit: 'km',
    icon: 'Route',
    trend: 15.3,
    color: 'brand',
  },
  {
    id: 'bins',
    label: 'Bins Collected',
    value: 1248,
    unit: 'units',
    icon: 'Trash2',
    trend: 6.7,
    color: 'teal',
  },
];
